using System.Collections.Immutable;
using QmlSharp.Qml.Ast;

#pragma warning disable MA0048

namespace QmlSharp.Qml.Emitter
{
    /// <summary>
    /// Indentation style for emitted QML.
    /// </summary>
    public enum IndentStyle
    {
        /// <summary>
        /// Use spaces for indentation.
        /// </summary>
        Spaces,

        /// <summary>
        /// Use tab characters for indentation.
        /// </summary>
        Tabs,
    }

    /// <summary>
    /// Quote style for emitted string literals.
    /// </summary>
    public enum QuoteStyle
    {
        /// <summary>
        /// Always use double quotes.
        /// </summary>
        Double,

        /// <summary>
        /// Always use single quotes.
        /// </summary>
        Single,

        /// <summary>
        /// Preserve source quote style when the AST carries that metadata.
        /// </summary>
        Preserve,
    }

    /// <summary>
    /// Semicolon handling in emitted QML.
    /// </summary>
    public enum SemicolonRule
    {
        /// <summary>
        /// Omit semicolons where optional.
        /// </summary>
        Omit,

        /// <summary>
        /// Emit semicolons after bindings and declarations.
        /// </summary>
        Always,

        /// <summary>
        /// Emit semicolons only where syntactically required.
        /// </summary>
        Essential,
    }

    /// <summary>
    /// Line ending style for emitted QML.
    /// </summary>
    public enum NewlineStyle
    {
        /// <summary>
        /// Unix-style line feed.
        /// </summary>
        Lf,

        /// <summary>
        /// Windows-style carriage return plus line feed.
        /// </summary>
        CrLf,
    }

    /// <summary>
    /// Options controlling QML emission behavior.
    /// </summary>
    public sealed record EmitOptions
    {
        /// <summary>
        /// Gets indentation character style.
        /// </summary>
        public IndentStyle IndentStyle { get; init; } = IndentStyle.Spaces;

        /// <summary>
        /// Gets number of spaces or tab stops per indent level.
        /// </summary>
        public int IndentSize { get; init; } = 4;

        /// <summary>
        /// Gets emitted line ending style.
        /// </summary>
        public NewlineStyle Newline { get; init; } = NewlineStyle.Lf;

        /// <summary>
        /// Gets advisory maximum line width. A value of -1 disables wrapping hints.
        /// </summary>
        public int MaxLineWidth { get; init; } = -1;

        /// <summary>
        /// Gets a value indicating whether to insert blank lines between document sections.
        /// </summary>
        public bool InsertBlankLinesBetweenSections { get; init; } = true;

        /// <summary>
        /// Gets a value indicating whether to insert blank lines between sibling objects.
        /// </summary>
        public bool InsertBlankLinesBetweenObjects { get; init; } = true;

        /// <summary>
        /// Gets a value indicating whether to insert blank lines between sibling functions.
        /// </summary>
        public bool InsertBlankLinesBetweenFunctions { get; init; } = true;

        /// <summary>
        /// Gets quote style for emitted string literals.
        /// </summary>
        public QuoteStyle QuoteStyle { get; init; } = QuoteStyle.Double;

        /// <summary>
        /// Gets a value indicating whether comments are emitted.
        /// </summary>
        public bool EmitComments { get; init; } = true;

        /// <summary>
        /// Gets a value indicating whether to emit a generated-code header comment.
        /// </summary>
        public bool EmitGeneratedHeader { get; init; }

        /// <summary>
        /// Gets generated-code header text.
        /// </summary>
        public string GeneratedHeaderText { get; init; } = "Generated by QmlSharp";

        /// <summary>
        /// Gets a value indicating whether output ends with a trailing newline.
        /// </summary>
        public bool TrailingNewline { get; init; } = true;

        /// <summary>
        /// Gets a value indicating whether member order is normalized before emission.
        /// </summary>
        public bool Normalize { get; init; }

        /// <summary>
        /// Gets a value indicating whether imports are sorted before emission.
        /// </summary>
        public bool SortImports { get; init; }

        /// <summary>
        /// Gets a value indicating whether empty objects are emitted on one line.
        /// </summary>
        public bool SingleLineEmptyObjects { get; init; } = true;

        /// <summary>
        /// Gets semicolon handling for bindings and declarations.
        /// </summary>
        public SemicolonRule SemicolonRule { get; init; } = SemicolonRule.Omit;
    }

    /// <summary>
    /// Options for emitting a single AST node fragment.
    /// </summary>
    public sealed record FragmentEmitOptions
    {
        /// <summary>
        /// Gets base emit options. Null uses default options.
        /// </summary>
        public EmitOptions? Options { get; init; }

        /// <summary>
        /// Gets starting indentation level. Zero means no indentation.
        /// </summary>
        public int IndentLevel { get; init; }
    }

    /// <summary>
    /// Core emitter interface. Converts QML AST trees to QML text.
    /// </summary>
    public interface IQmlEmitter
    {
        /// <summary>
        /// Emit a complete QML document as text.
        /// </summary>
        /// <param name="document">The QML document AST to emit.</param>
        /// <param name="options">Emission options. Null uses defaults.</param>
        /// <returns>Syntactically correct QML text.</returns>
        string Emit(QmlDocument document, EmitOptions? options = null);

        /// <summary>
        /// Emit a single AST node as a text fragment.
        /// </summary>
        /// <param name="node">The AST node to emit.</param>
        /// <param name="options">Fragment emission options.</param>
        /// <returns>Text representation of the node.</returns>
        string EmitFragment(AstNode node, FragmentEmitOptions? options = null);

        /// <summary>
        /// Emit a complete QML document with source map tracking.
        /// </summary>
        /// <param name="document">The QML document AST to emit.</param>
        /// <param name="options">Emission options. Null uses defaults.</param>
        /// <returns>Text and source map result.</returns>
        EmitResult EmitWithSourceMap(QmlDocument document, EmitOptions? options = null);
    }

    /// <summary>
    /// Result of emitting a QML document with source map tracking.
    /// </summary>
    public sealed record EmitResult
    {
        /// <summary>
        /// Gets emitted QML text.
        /// </summary>
        public required string Text { get; init; }

        /// <summary>
        /// Gets source map recording output positions.
        /// </summary>
        public required ISourceMap SourceMap { get; init; }
    }

    /// <summary>
    /// A span within emitted output text. Lines and columns are 1-based.
    /// </summary>
    public sealed record OutputSpan
    {
        /// <summary>
        /// Gets start line.
        /// </summary>
        public required int StartLine { get; init; }

        /// <summary>
        /// Gets start column.
        /// </summary>
        public required int StartColumn { get; init; }

        /// <summary>
        /// Gets inclusive end line.
        /// </summary>
        public required int EndLine { get; init; }

        /// <summary>
        /// Gets inclusive end column.
        /// </summary>
        public required int EndColumn { get; init; }
    }

    /// <summary>
    /// A source-map entry linking an AST node to its emitted output span.
    /// </summary>
    public sealed record SourceMapEntry
    {
        /// <summary>
        /// Gets emitted AST node.
        /// </summary>
        public required AstNode Node { get; init; }

        /// <summary>
        /// Gets node kind string for serialization and diagnostics.
        /// </summary>
        public required string NodeKind { get; init; }

        /// <summary>
        /// Gets emitted output span for the node.
        /// </summary>
        public required OutputSpan OutputSpan { get; init; }
    }

    /// <summary>
    /// Read-only source map over emitted output positions.
    /// </summary>
    public interface ISourceMap
    {
        /// <summary>
        /// Gets all source map entries in deterministic order.
        /// </summary>
        IReadOnlyList<SourceMapEntry> Entries { get; }

        /// <summary>
        /// Get the output span for a specific AST node.
        /// </summary>
        /// <param name="node">The AST node to locate.</param>
        /// <returns>The output span, or null when the node was not mapped.</returns>
        OutputSpan? GetOutputSpan(AstNode node);

        /// <summary>
        /// Get all AST nodes emitted on the given output line.
        /// </summary>
        /// <param name="line">1-based output line.</param>
        /// <returns>Nodes emitted on the line.</returns>
        IReadOnlyList<AstNode> GetNodesAtLine(int line);

        /// <summary>
        /// Get the innermost AST node at an output position.
        /// </summary>
        /// <param name="line">1-based output line.</param>
        /// <param name="column">1-based output column.</param>
        /// <returns>The innermost node at the position, or null.</returns>
        AstNode? GetInnermostNodeAt(int line, int column);

        /// <summary>
        /// Convert the source map to a JSON-serializable DTO.
        /// </summary>
        /// <returns>JSON DTO for this source map.</returns>
        SourceMapJson ToJson();
    }

    /// <summary>
    /// JSON-serializable source-map DTO.
    /// </summary>
    public sealed record SourceMapJson
    {
        /// <summary>
        /// Gets serialized entries.
        /// </summary>
        public required ImmutableArray<SourceMapEntryJson> Entries { get; init; }
    }

    /// <summary>
    /// JSON-serializable source-map entry DTO.
    /// </summary>
    public sealed record SourceMapEntryJson
    {
        /// <summary>
        /// Gets node kind string.
        /// </summary>
        public required string NodeKind { get; init; }

        /// <summary>
        /// Gets emitted output span.
        /// </summary>
        public required OutputSpan Span { get; init; }
    }
}

#pragma warning restore MA0048
