// <auto-generated />

namespace QmlSharp.QtQuick.Controls;

using QmlSharp.Core;
using QmlSharp.Dsl;
using System;
using System.Collections.Immutable;

/// <summary>
/// Properties for Button.
/// </summary>
public interface IButtonProps
{
    /// <summary>
    /// Gets the checked property value.
    /// </summary>
    bool? Checked { get; }
    /// <summary>
    /// Gets the text property value.
    /// </summary>
    string? Text { get; }
    /// <summary>
    /// Gets the width property value.
    /// </summary>
    double? Width { get; }
}

/// <summary>
/// Builder for Button.
/// </summary>
public interface IButtonBuilder : IObjectBuilder
{
    /// <summary>
    /// Sets checked.
    /// </summary>
    IButtonBuilder Checked(bool value);
    IButtonBuilder CheckedBind(string expr);
    /// <summary>
    /// Sets text.
    /// </summary>
    IButtonBuilder Text(string value);
    IButtonBuilder TextBind(string expr);
    /// <summary>
    /// Sets width.
    /// </summary>
    IButtonBuilder Width(double value);
    IButtonBuilder WidthBind(string expr);
    /// <summary>
    /// Handles clicked.
    /// </summary>
    IButtonBuilder OnClicked(Action handler);
    IButtonBuilder OnClicked(string body);
    /// <summary>
    /// Invokes click.
    /// </summary>
    IButtonBuilder Click();
}

/// <summary>
/// Factory methods for Button.
/// </summary>
public static class ButtonFactory
{
    /// <summary>
    /// Creates a Button builder.
    /// </summary>
    public static IButtonBuilder Button()
    {
        return ObjectFactory.Create<IButtonBuilder>("Button", CreateMetadata());
    }

    private static ObjectBuilderMetadata CreateMetadata()
    {
        return new ObjectBuilderMetadata(
        ImmutableArray.Create<PropertyMethodMetadata>(new PropertyMethodMetadata("Checked", "checked", true, true), new PropertyMethodMetadata("Text", "text", true, true), new PropertyMethodMetadata("Width", "width", true, true)),
        ImmutableArray<GroupedPropertyMethodMetadata>.Empty,
        ImmutableArray<AttachedPropertyMethodMetadata>.Empty,
        ImmutableArray.Create<SignalMethodMetadata>(new SignalMethodMetadata("OnClicked", "onClicked")));
    }
}
