// <auto-generated />

#nullable enable

namespace QmlSharp.QtQuick;

using QmlSharp.Core;
using QmlSharp.Dsl;
using System;
using System.Collections.Immutable;

/// <summary>
/// Builder for the Border grouped property.
/// </summary>
public interface IRectangleBorderBuilder : IPropertyCollector
{
    /// <summary>
    /// Sets border.color.
    /// </summary>
    IRectangleBorderBuilder Color(QmlColor value);
    IRectangleBorderBuilder ColorBind(string expr);
    /// <summary>
    /// Sets border.width.
    /// </summary>
    IRectangleBorderBuilder Width(double value);
    IRectangleBorderBuilder WidthBind(string expr);
}

/// <summary>
/// Builder for Layout attached properties.
/// </summary>
public interface ILayoutAttachedBuilder : IPropertyCollector
{
    /// <summary>
    /// Sets fillHeight.
    /// </summary>
    ILayoutAttachedBuilder FillHeight(bool value);
    ILayoutAttachedBuilder FillHeightBind(string expr);
    /// <summary>
    /// Sets fillWidth.
    /// </summary>
    ILayoutAttachedBuilder FillWidth(bool value);
    ILayoutAttachedBuilder FillWidthBind(string expr);
}

/// <summary>
/// Properties for Rectangle.
/// </summary>
public interface IRectangleProps
{
    /// <summary>
    /// Gets the color property value.
    /// </summary>
    QmlColor? Color { get; }
    /// <summary>
    /// Gets the width property value.
    /// </summary>
    double? Width { get; }
}

/// <summary>
/// Builder for Rectangle.
/// </summary>
public interface IRectangleBuilder : IObjectBuilder
{
    /// <summary>
    /// Sets color.
    /// </summary>
    IRectangleBuilder Color(QmlColor value);
    IRectangleBuilder ColorBind(string expr);
    /// <summary>
    /// Sets width.
    /// </summary>
    IRectangleBuilder Width(double value);
    IRectangleBuilder WidthBind(string expr);
    /// <summary>
    /// Configures the Border grouped property.
    /// </summary>
    IRectangleBuilder Border(Action<IRectangleBorderBuilder> setup);
    /// <summary>
    /// Configures Layout attached properties.
    /// </summary>
    IRectangleBuilder Layout(Action<ILayoutAttachedBuilder> setup);
    /// <summary>
    /// Handles colorChanged.
    /// </summary>
    IRectangleBuilder OnColorChanged(Action handler);
    IRectangleBuilder OnColorChanged(string body);
    /// <summary>
    /// Adds a child object to the data default property.
    /// </summary>
    new IRectangleBuilder Child(IObjectBuilder child);
    /// <summary>
    /// Adds child objects to the data default property.
    /// </summary>
    new IRectangleBuilder Children(params IObjectBuilder[] children);
}

/// <summary>
/// Factory methods for Rectangle.
/// </summary>
public static class RectangleFactory
{
    /// <summary>
    /// Creates a Rectangle builder.
    /// </summary>
    public static IRectangleBuilder Rectangle()
    {
        return ObjectFactory.Create<IRectangleBuilder>("Rectangle", CreateMetadata());
    }

    private static ObjectBuilderMetadata CreateMetadata()
    {
        return new ObjectBuilderMetadata(
        ImmutableArray.Create<PropertyMethodMetadata>(new PropertyMethodMetadata("BorderColor", "border.color", true, true), new PropertyMethodMetadata("BorderWidth", "border.width", true, true), new PropertyMethodMetadata("Color", "color", true, true), new PropertyMethodMetadata("Width", "width", true, true)),
        ImmutableArray.Create<GroupedPropertyMethodMetadata>(new GroupedPropertyMethodMetadata("Border", "border", new PropertyCollectorMetadata(ImmutableArray.Create<PropertyMethodMetadata>(new PropertyMethodMetadata("Color", "color", true, true), new PropertyMethodMetadata("Width", "width", true, true)), ImmutableArray<SignalMethodMetadata>.Empty))),
        ImmutableArray.Create<AttachedPropertyMethodMetadata>(new AttachedPropertyMethodMetadata("Layout", "Layout", new PropertyCollectorMetadata(ImmutableArray.Create<PropertyMethodMetadata>(new PropertyMethodMetadata("FillHeight", "fillHeight", true, true), new PropertyMethodMetadata("FillWidth", "fillWidth", true, true)), ImmutableArray<SignalMethodMetadata>.Empty))),
        ImmutableArray.Create<SignalMethodMetadata>(new SignalMethodMetadata("OnColorChanged", "onColorChanged")));
    }
}
