// <auto-generated />

namespace QmlSharp.QtQuick;

using QmlSharp.Core;
using QmlSharp.Dsl;
using System;
using System.Collections.Immutable;

/// <summary>
/// QML enum TextWrapMode.
/// </summary>
public enum TextWrapMode
{
    NoWrap = 0,
    WordWrap = 1
}

/// <summary>
/// Properties for Text.
/// </summary>
public interface ITextProps
{
    /// <summary>
    /// Gets the lineCount property value.
    /// </summary>
    int? LineCount { get; }
    /// <summary>
    /// Gets the text property value.
    /// </summary>
    string? Text { get; }
    /// <summary>
    /// Gets the width property value.
    /// </summary>
    double? Width { get; }
    /// <summary>
    /// Gets the wrapMode property value.
    /// </summary>
    TextWrapMode? WrapMode { get; }
}

/// <summary>
/// Builder for Text.
/// </summary>
public interface ITextBuilder : IObjectBuilder
{
    /// <summary>
    /// Sets text.
    /// </summary>
    ITextBuilder Text(string value);
    ITextBuilder TextBind(string expr);
    /// <summary>
    /// Sets width.
    /// </summary>
    ITextBuilder Width(double value);
    ITextBuilder WidthBind(string expr);
    /// <summary>
    /// Sets wrapMode.
    /// </summary>
    ITextBuilder WrapMode(TextWrapMode value);
    ITextBuilder WrapModeBind(string expr);
    /// <summary>
    /// Handles textChanged.
    /// </summary>
    ITextBuilder OnTextChanged(Action handler);
    ITextBuilder OnTextChanged(string body);
    /// <summary>
    /// Invokes append.
    /// </summary>
    ITextBuilder Append(string value);
}

/// <summary>
/// Factory methods for Text.
/// </summary>
public static class TextFactory
{
    /// <summary>
    /// Creates a Text builder.
    /// </summary>
    public static ITextBuilder Text()
    {
        return ObjectFactory.Create<ITextBuilder>("Text", CreateMetadata());
    }

    private static ObjectBuilderMetadata CreateMetadata()
    {
        return new ObjectBuilderMetadata(
        ImmutableArray.Create<PropertyMethodMetadata>(new PropertyMethodMetadata("LineCount", "lineCount", false, false), new PropertyMethodMetadata("Text", "text", true, true), new PropertyMethodMetadata("Width", "width", true, true), new PropertyMethodMetadata("WrapMode", "wrapMode", true, true)),
        ImmutableArray<GroupedPropertyMethodMetadata>.Empty,
        ImmutableArray<AttachedPropertyMethodMetadata>.Empty,
        ImmutableArray.Create<SignalMethodMetadata>(new SignalMethodMetadata("OnTextChanged", "onTextChanged")));
    }
}
