using QmlSharp.Qml.Emitter.Tests.Helpers;

namespace QmlSharp.Qml.Emitter.Tests.Options
{
    public sealed class EmitOptionsContractTests
    {
        [Fact]
        [Trait("Category", TestCategories.Smoke)]
        public void Options_DefaultEmitOptions_MatchApiDesignContract()
        {
            EmitOptions options = new();

            Assert.Equal(IndentStyle.Spaces, options.IndentStyle);
            Assert.Equal(4, options.IndentSize);
            Assert.Equal(NewlineStyle.Lf, options.Newline);
            Assert.Equal(-1, options.MaxLineWidth);
            Assert.True(options.InsertBlankLinesBetweenSections);
            Assert.True(options.InsertBlankLinesBetweenObjects);
            Assert.True(options.InsertBlankLinesBetweenFunctions);
            Assert.Equal(QuoteStyle.Double, options.QuoteStyle);
            Assert.True(options.EmitComments);
            Assert.False(options.EmitGeneratedHeader);
            Assert.Equal("Generated by QmlSharp", options.GeneratedHeaderText);
            Assert.True(options.TrailingNewline);
            Assert.False(options.Normalize);
            Assert.False(options.SortImports);
            Assert.True(options.SingleLineEmptyObjects);
            Assert.Equal(SemicolonRule.Omit, options.SemicolonRule);
        }

        [Fact]
        [Trait("Category", TestCategories.Smoke)]
        public void Options_DefaultFragmentOptions_MatchApiDesignContract()
        {
            FragmentEmitOptions options = new();

            Assert.Null(options.Options);
            Assert.Equal(0, options.IndentLevel);
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Options_WithExpression_CreatesCustomizedImmutableCopy()
        {
            EmitOptions defaults = new();
            EmitOptions customized = defaults with
            {
                IndentStyle = IndentStyle.Tabs,
                QuoteStyle = QuoteStyle.Single,
                SemicolonRule = SemicolonRule.Always,
            };

            Assert.Equal(IndentStyle.Spaces, defaults.IndentStyle);
            Assert.Equal(IndentStyle.Tabs, customized.IndentStyle);
            Assert.Equal(QuoteStyle.Single, customized.QuoteStyle);
            Assert.Equal(SemicolonRule.Always, customized.SemicolonRule);
        }
    }
}
