using QmlSharp.Qml.Emitter.Tests.Helpers;

namespace QmlSharp.Qml.Emitter.Tests.Options
{
    public sealed class ResolvedEmitOptionsTests
    {
        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Options_DefaultResolution_AppliesApiDesignDefaults()
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(null);

            Assert.Equal("    ", options.IndentString);
            Assert.Equal("\n", options.NewlineString);
            Assert.Equal('"', options.QuoteChar);
            Assert.Equal(QuoteStyle.Double, options.QuoteStyle);
            Assert.True(options.EmitComments);
            Assert.False(options.Normalize);
            Assert.False(options.SortImports);
            Assert.True(options.TrailingNewline);
            Assert.True(options.InsertBlankLinesBetweenSections);
            Assert.True(options.InsertBlankLinesBetweenObjects);
            Assert.True(options.InsertBlankLinesBetweenFunctions);
            Assert.False(options.EmitGeneratedHeader);
            Assert.Equal("Generated by QmlSharp", options.GeneratedHeaderText);
            Assert.True(options.SingleLineEmptyObjects);
            Assert.Equal(SemicolonRule.Omit, options.SemicolonRule);
            Assert.Equal(-1, options.MaxLineWidth);
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_01_IndentStyleTabs_ResolvesTabIndentString()
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { IndentStyle = IndentStyle.Tabs });

            Assert.Equal("\t", options.IndentString);
        }

        [Theory]
        [InlineData(2, "  ")]
        [InlineData(8, "        ")]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_02_OPT_03_IndentSize_ResolvesSpaceIndentString(int indentSize, string expectedIndent)
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { IndentSize = indentSize });

            Assert.Equal(expectedIndent, options.IndentString);
        }

        [Theory]
        [InlineData(NewlineStyle.CrLf, "\r\n")]
        [InlineData(NewlineStyle.Lf, "\n")]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_04_OPT_05_NewlineStyle_ResolvesConfiguredLineEnding(NewlineStyle newline, string expected)
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { Newline = newline });

            Assert.Equal(expected, options.NewlineString);
        }

        [Theory]
        [InlineData(QuoteStyle.Single, '\'')]
        [InlineData(QuoteStyle.Double, '"')]
        [InlineData(QuoteStyle.Preserve, '"')]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_06_OPT_07_OPT_08_QuoteStyle_ResolvesQuoteCharacter(QuoteStyle quoteStyle, char expected)
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { QuoteStyle = quoteStyle });

            Assert.Equal(expected, options.QuoteChar);
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_08_QuoteStylePreserve_FallsBackToDoubleQuoteWhenAstHasNoQuoteMetadata()
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { QuoteStyle = QuoteStyle.Preserve });

            Assert.Equal("\"hello\"", options.QuoteStringLiteral("hello"));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_09_Through_OPT_13_BooleanOptions_ArePreservedByResolution()
        {
            EmitOptions source = new()
            {
                EmitComments = false,
                EmitGeneratedHeader = true,
                GeneratedHeaderText = "Custom header",
                TrailingNewline = false,
                Normalize = true,
                SortImports = true,
                InsertBlankLinesBetweenSections = false,
                InsertBlankLinesBetweenObjects = false,
                InsertBlankLinesBetweenFunctions = false,
                SingleLineEmptyObjects = false,
                MaxLineWidth = 120,
            };

            ResolvedEmitOptions options = ResolvedEmitOptions.From(source);

            Assert.False(options.EmitComments);
            Assert.True(options.EmitGeneratedHeader);
            Assert.Equal("Custom header", options.GeneratedHeaderText);
            Assert.False(options.TrailingNewline);
            Assert.True(options.Normalize);
            Assert.True(options.SortImports);
            Assert.False(options.InsertBlankLinesBetweenSections);
            Assert.False(options.InsertBlankLinesBetweenObjects);
            Assert.False(options.InsertBlankLinesBetweenFunctions);
            Assert.False(options.SingleLineEmptyObjects);
            Assert.Equal(120, options.MaxLineWidth);
        }

        [Theory]
        [InlineData(SemicolonRule.Always, false, ";")]
        [InlineData(SemicolonRule.Always, true, ";")]
        [InlineData(SemicolonRule.Essential, false, "")]
        [InlineData(SemicolonRule.Essential, true, ";")]
        [InlineData(SemicolonRule.Omit, false, "")]
        [InlineData(SemicolonRule.Omit, true, "")]
        [Trait("Category", TestCategories.Contract)]
        public void OPT_14_OPT_15_OPT_16_SemicolonRules_ResolveDeterministicSuffixes(
            SemicolonRule rule,
            bool syntacticallyRequired,
            string expected)
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { SemicolonRule = rule });

            Assert.Equal(expected, options.GetSemicolonSuffix(syntacticallyRequired));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Options_MaxLineWidth_IsResolvedAsAdvisoryValue()
        {
            ResolvedEmitOptions options = ResolvedEmitOptions.From(new EmitOptions { MaxLineWidth = 40 });

            Assert.Equal(40, options.MaxLineWidth);
        }

        [Theory]
        [InlineData(0)]
        [InlineData(-2)]
        [Trait("Category", TestCategories.Contract)]
        public void Options_InvalidIndentSize_ThrowsArgumentOutOfRangeException(int indentSize)
        {
            EmitOptions options = new() { IndentSize = indentSize };

            _ = Assert.Throws<ArgumentOutOfRangeException>(() => ResolvedEmitOptions.From(options));
        }

        [Theory]
        [InlineData(-2)]
        [InlineData(0)]
        [Trait("Category", TestCategories.Contract)]
        public void Options_InvalidMaxLineWidth_ThrowsArgumentOutOfRangeException(int maxLineWidth)
        {
            EmitOptions options = new() { MaxLineWidth = maxLineWidth };

            _ = Assert.Throws<ArgumentOutOfRangeException>(() => ResolvedEmitOptions.From(options));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Options_InvalidEnumValues_ThrowArgumentOutOfRangeException()
        {
            _ = Assert.Throws<ArgumentOutOfRangeException>(
                () => ResolvedEmitOptions.From(new EmitOptions { IndentStyle = (IndentStyle)42 }));
            _ = Assert.Throws<ArgumentOutOfRangeException>(
                () => ResolvedEmitOptions.From(new EmitOptions { Newline = (NewlineStyle)42 }));
            _ = Assert.Throws<ArgumentOutOfRangeException>(
                () => ResolvedEmitOptions.From(new EmitOptions { QuoteStyle = (QuoteStyle)42 }));
            _ = Assert.Throws<ArgumentOutOfRangeException>(
                () => ResolvedEmitOptions.From(new EmitOptions { SemicolonRule = (SemicolonRule)42 }));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Options_NullGeneratedHeaderText_ThrowsArgumentException()
        {
            EmitOptions options = new() { GeneratedHeaderText = null! };

            _ = Assert.Throws<ArgumentException>(() => ResolvedEmitOptions.From(options));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void Emitter_InvalidOptions_ValidateBeforeUnsupportedEmissionStub()
        {
            IQmlEmitter emitter = new QmlEmitter();
            QmlDocument document = AstFixtureFactory.MinimalDocument();
            EmitOptions options = new() { IndentSize = 0 };

            _ = Assert.Throws<ArgumentOutOfRangeException>(() => emitter.Emit(document, options));
        }

        [Fact]
        [Trait("Category", TestCategories.Contract)]
        public void FragmentOptions_NegativeIndentLevel_ThrowsArgumentOutOfRangeException()
        {
            IQmlEmitter emitter = new QmlEmitter();
            FragmentEmitOptions options = new() { IndentLevel = -1 };
            ObjectDefinitionNode node = new() { TypeName = "Item" };

            _ = Assert.Throws<ArgumentOutOfRangeException>(() => emitter.EmitFragment(node, options));
        }
    }
}
