using System.Text;

namespace QmlSharp.Dsl.Generator
{
    /// <summary>
    /// Emits deterministic C# source files from generated DSL metadata.
    /// </summary>
    public sealed class CodeEmitter : ICodeEmitter
    {
        private const string Indent = "    ";
        public string EmitTypeFile(GeneratedTypeCode typeCode, CodeEmitOptions options)
        {
            ArgumentNullException.ThrowIfNull(typeCode);
            ThrowIfInvalidType(typeCode);

            CodeWriter writer = new();
            WriteHeader(writer, options);
            WriteNullableDirective(writer);
            writer.AppendLine($"namespace {GetNamespace(typeCode.ModuleUri)};");
            writer.AppendLine();
            foreach (string usingDirective in GetTypeFileUsings())
            {
                writer.AppendLine($"using {usingDirective};");
            }

            writer.AppendLine();
            foreach (GeneratedEnum generatedEnum in SortEnums(typeCode.Enums))
            {
                WriteEnum(writer, generatedEnum, options);
                writer.AppendLine();
            }

            foreach (GroupedSurface groupedSurface in GetGroupedSurfaces(typeCode))
            {
                WriteGroupedBuilder(writer, groupedSurface, options);
                writer.AppendLine();
            }

            foreach (GeneratedAttachedType attachedType in SortAttachedTypes(typeCode.AttachedTypes))
            {
                WriteAttachedBuilder(writer, attachedType, options);
                writer.AppendLine();
            }

            WritePropsInterface(writer, typeCode, options);
            writer.AppendLine();
            WriteBuilderInterface(writer, typeCode, options);
            writer.AppendLine();
            if (typeCode.IsCreatable)
            {
                WriteFactoryClass(writer, typeCode, options);
            }

            return writer.ToString();
        }

        public string EmitIndexFile(
            ImmutableArray<GeneratedTypeCode> types,
            ImmutableArray<GeneratedEnum> enums)
        {
            CodeWriter writer = new();
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine();
            WriteNullableDirective(writer);

            string moduleUri = GetIndexModuleUri(types, enums);
            writer.AppendLine($"namespace {GetNamespace(moduleUri)};");
            writer.AppendLine();
            writer.AppendLine("using QmlSharp.Dsl;");
            writer.AppendLine();
            writer.AppendLine($"public static class {GetModuleClassName(moduleUri)}Factories");
            writer.AppendLine("{");

            foreach (GeneratedTypeCode type in types
                         .Where(static type => type.IsCreatable)
                         .OrderBy(static type => type.FactoryName, StringComparer.Ordinal)
                         .ThenBy(static type => type.QmlName, StringComparer.Ordinal))
            {
                writer.AppendLine($"{Indent}public static {type.BuilderInterfaceName} {type.FactoryName}() => {type.FactoryName}Factory.{type.FactoryName}();");
            }

            writer.AppendLine("}");
            return writer.ToString();
        }

        public string EmitProjectFile(GeneratedPackage package)
        {
            ArgumentNullException.ThrowIfNull(package);

            CodeWriter writer = new();
            writer.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
            writer.AppendLine("  <PropertyGroup>");
            writer.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
            writer.AppendLine("    <Nullable>enable</Nullable>");
            writer.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");
            writer.AppendLine($"    <PackageId>{EscapeXml(package.PackageName)}</PackageId>");
            writer.AppendLine($"    <Version>{EscapeXml(package.PackageVersion)}</Version>");
            writer.AppendLine("    <GenerateDocumentationFile>true</GenerateDocumentationFile>");
            writer.AppendLine("  </PropertyGroup>");

            ImmutableArray<string> dependencies = package.Dependencies
                .Order(StringComparer.Ordinal)
                .ToImmutableArray();
            if (!dependencies.IsDefaultOrEmpty)
            {
                writer.AppendLine("  <ItemGroup>");
                foreach (string dependency in dependencies)
                {
                    writer.AppendLine($"    <PackageReference Include=\"{EscapeXml(dependency)}\" Version=\"{EscapeXml(package.PackageVersion)}\" />");
                }

                writer.AppendLine("  </ItemGroup>");
            }

            writer.AppendLine("</Project>");
            return writer.ToString();
        }

        public string EmitReadme(GeneratedPackage package)
        {
            ArgumentNullException.ThrowIfNull(package);

            CodeWriter writer = new();
            writer.AppendLine($"# {package.PackageName}");
            writer.AppendLine();
            writer.AppendLine($"Generated QmlSharp DSL bindings for `{package.ModuleUri}`.");
            writer.AppendLine();
            writer.AppendLine("This package is generated from Qt registry metadata. Do not edit generated source files by hand.");
            return writer.ToString();
        }

        public string EmitCommonTypes()
        {
            CodeWriter writer = new();
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine();
            WriteNullableDirective(writer);
            writer.AppendLine("namespace QmlSharp.Core;");
            writer.AppendLine();
            writer.AppendLine("// Common value types are implemented in QmlSharp.Core and forwarded to generated packages.");
            writer.AppendLine("// QmlColor, QmlPoint, QmlSize, QmlRect, QmlFont, Vector2, Vector3, Vector4, Quaternion, Matrix4x4");
            return writer.ToString();
        }

        public string EmitViewModelHelpers(ViewModelBindingInfo integration)
        {
            ArgumentNullException.ThrowIfNull(integration);

            CodeWriter writer = new();
            writer.AppendLine("// <auto-generated />");
            writer.AppendLine();
            WriteNullableDirective(writer);
            writer.AppendLine("namespace QmlSharp.Dsl;");
            writer.AppendLine();
            writer.AppendLine($"public abstract class {integration.ClassName}");
            writer.AppendLine("{");
            foreach (ViewModelStateInfo state in integration.States.OrderBy(static state => state.FieldName, StringComparer.Ordinal))
            {
                writer.AppendLine($"{Indent}public abstract {state.CSharpType} {state.FieldName} {{ get; }}");
            }

            foreach (ViewModelCommandInfo command in integration.Commands.OrderBy(static command => command.MethodName, StringComparer.Ordinal))
            {
                string parameters = string.Join(", ", command.Parameters.Select(static parameter => $"{parameter.CSharpType} {parameter.Name}"));
                writer.AppendLine($"{Indent}public abstract void {command.MethodName}({parameters});");
            }

            writer.AppendLine("}");
            return writer.ToString();
        }

        private static void WriteHeader(CodeWriter writer, CodeEmitOptions options)
        {
            if (!string.IsNullOrWhiteSpace(options.HeaderComment))
            {
                foreach (string line in NormalizeLines(options.HeaderComment))
                {
                    writer.AppendLine(line);
                }
            }
            else
            {
                writer.AppendLine("// <auto-generated />");
            }

            writer.AppendLine();
        }

        private static void WriteNullableDirective(CodeWriter writer)
        {
            writer.AppendLine("#nullable enable");
            writer.AppendLine();
        }

        private static void WritePropsInterface(CodeWriter writer, GeneratedTypeCode typeCode, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"Properties for {typeCode.QmlName}.");
            if (typeCode.IsDeprecated && options.MarkDeprecated)
            {
                writer.AppendLine("[Obsolete]");
            }

            writer.AppendLine($"public interface {typeCode.PropsInterfaceName}");
            writer.AppendLine("{");
            foreach (GeneratedProperty property in SortProperties(typeCode.Properties)
                         .Where(static property => !IsGroupedProperty(property)))
            {
                WriteXmlDoc(writer, options, $"Gets the {GetQmlPropertyName(property)} property value.", Indent);
                writer.AppendLine($"{Indent}{property.CSharpType}? {property.Name} {{ get; }}");
            }

            writer.AppendLine("}");
        }

        private static void WriteBuilderInterface(CodeWriter writer, GeneratedTypeCode typeCode, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"Builder for {typeCode.QmlName}.");
            if (typeCode.IsDeprecated && options.MarkDeprecated)
            {
                writer.AppendLine("[Obsolete]");
            }

            writer.AppendLine($"public interface {typeCode.BuilderInterfaceName} : IObjectBuilder");
            writer.AppendLine("{");
            foreach (GeneratedProperty property in SortProperties(typeCode.Properties)
                         .Where(static property => !property.IsReadOnly && !IsGroupedProperty(property)))
            {
                WriteGeneratedXmlDoc(writer, options, property.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{EnsureInterfaceSignature(property.SetterSignature)};");
                if (!string.IsNullOrWhiteSpace(property.BindSignature))
                {
                    writer.AppendLine($"{Indent}{EnsureInterfaceSignature(property.BindSignature)};");
                }
            }

            foreach (GroupedSurface groupedSurface in GetGroupedSurfaces(typeCode))
            {
                WriteXmlDoc(writer, options, $"Configures the {groupedSurface.GroupName} grouped property.", Indent);
                writer.AppendLine($"{Indent}{typeCode.BuilderInterfaceName} {groupedSurface.GroupName}(Action<{groupedSurface.BuilderInterfaceName}> setup);");
            }

            foreach (GeneratedAttachedType attachedType in SortAttachedTypes(typeCode.AttachedTypes))
            {
                WriteXmlDoc(writer, options, $"Configures {attachedType.MethodName} attached properties.", Indent);
                writer.AppendLine($"{Indent}{typeCode.BuilderInterfaceName} {attachedType.MethodName}(Action<{attachedType.BuilderInterfaceName}> setup);");
            }

            WriteSignalMethods(writer, typeCode, options);

            foreach (GeneratedMethod method in SortMethods(typeCode.Methods))
            {
                WriteGeneratedXmlDoc(writer, options, method.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{EnsureInterfaceSignature(method.Signature)};");
            }

            if (typeCode.DefaultProperty is not null)
            {
                if (typeCode.DefaultProperty.GenerateChildMethod)
                {
                    WriteXmlDoc(writer, options, $"Adds a child object to the {typeCode.DefaultProperty.PropertyName} default property.", Indent);
                    writer.AppendLine($"{Indent}new {typeCode.BuilderInterfaceName} Child(IObjectBuilder child);");
                }

                if (typeCode.DefaultProperty.GenerateChildrenMethod)
                {
                    WriteXmlDoc(writer, options, $"Adds child objects to the {typeCode.DefaultProperty.PropertyName} default property.", Indent);
                    writer.AppendLine($"{Indent}new {typeCode.BuilderInterfaceName} Children(params IObjectBuilder[] children);");
                }
            }

            writer.AppendLine("}");
        }

        private static void WriteSignalMethods(CodeWriter writer, GeneratedTypeCode typeCode, CodeEmitOptions options)
        {
            foreach (GeneratedSignal signal in SortSignals(typeCode.Signals))
            {
                WriteGeneratedXmlDoc(writer, options, signal.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{EnsureInterfaceSignature(signal.HandlerSignature)};");
                writer.AppendLine($"{Indent}{typeCode.BuilderInterfaceName} {signal.HandlerName}(string body);");
            }
        }

        private static void WriteFactoryClass(CodeWriter writer, GeneratedTypeCode typeCode, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"Factory methods for {typeCode.QmlName}.");
            writer.AppendLine($"public static class {typeCode.FactoryName}Factory");
            writer.AppendLine("{");
            WriteXmlDoc(writer, options, $"Creates a {typeCode.QmlName} builder.", Indent);
            writer.AppendLine($"{Indent}public static {typeCode.BuilderInterfaceName} {typeCode.FactoryName}()");
            writer.AppendLine($"{Indent}{{");
            writer.AppendLine($"{Indent}{Indent}return ObjectFactory.Create<{typeCode.BuilderInterfaceName}>(\"{EscapeStringLiteral(typeCode.QmlName)}\", CreateMetadata());");
            writer.AppendLine($"{Indent}}}");
            writer.AppendLine();
            writer.AppendLine($"{Indent}private static ObjectBuilderMetadata CreateMetadata()");
            writer.AppendLine($"{Indent}{{");
            writer.AppendLine($"{Indent}{Indent}return new ObjectBuilderMetadata(");
            WritePropertyMetadata(writer, typeCode);
            writer.AppendLine(",");
            WriteGroupedMetadata(writer, typeCode);
            writer.AppendLine(",");
            WriteAttachedMetadata(writer, typeCode);
            writer.AppendLine(",");
            WriteSignalMetadata(writer, typeCode);
            writer.AppendLine(");");
            writer.AppendLine($"{Indent}}}");
            writer.AppendLine("}");
        }

        private static void WriteEnum(CodeWriter writer, GeneratedEnum generatedEnum, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"QML enum {generatedEnum.Name}.");
            foreach (string line in NormalizeLines(generatedEnum.Code))
            {
                writer.AppendLine(line);
            }
        }

        private static void WriteGroupedBuilder(CodeWriter writer, GroupedSurface groupedSurface, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"Builder for the {groupedSurface.GroupName} grouped property.");
            writer.AppendLine($"public interface {groupedSurface.BuilderInterfaceName} : IPropertyCollector");
            writer.AppendLine("{");
            foreach (GeneratedProperty property in groupedSurface.Properties.Where(static property => !property.IsReadOnly))
            {
                WriteGeneratedXmlDoc(writer, options, property.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{groupedSurface.BuilderInterfaceName} {GetLocalGroupedMethodName(property)}({property.CSharpType} value);");
                if (!string.IsNullOrWhiteSpace(property.BindSignature))
                {
                    writer.AppendLine($"{Indent}{groupedSurface.BuilderInterfaceName} {GetLocalGroupedMethodName(property)}Bind(string expr);");
                }
            }

            writer.AppendLine("}");
        }

        private static void WriteAttachedBuilder(CodeWriter writer, GeneratedAttachedType attachedType, CodeEmitOptions options)
        {
            WriteXmlDoc(writer, options, $"Builder for {attachedType.MethodName} attached properties.");
            writer.AppendLine($"public interface {attachedType.BuilderInterfaceName} : IPropertyCollector");
            writer.AppendLine("{");
            foreach (GeneratedProperty property in SortProperties(attachedType.Properties).Where(static property => !property.IsReadOnly))
            {
                WriteGeneratedXmlDoc(writer, options, property.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{attachedType.BuilderInterfaceName} {property.Name}({property.CSharpType} value);");
                if (!string.IsNullOrWhiteSpace(property.BindSignature))
                {
                    writer.AppendLine($"{Indent}{attachedType.BuilderInterfaceName} {property.Name}Bind(string expr);");
                }
            }

            foreach (GeneratedSignal signal in SortSignals(attachedType.Signals))
            {
                WriteGeneratedXmlDoc(writer, options, signal.XmlDoc, Indent);
                writer.AppendLine($"{Indent}{EnsureInterfaceSignature(signal.HandlerSignature.Replace("IObjectBuilder", attachedType.BuilderInterfaceName, StringComparison.Ordinal))};");
                writer.AppendLine($"{Indent}{attachedType.BuilderInterfaceName} {signal.HandlerName}(string body);");
            }

            writer.AppendLine("}");
        }

        private static void WritePropertyMetadata(CodeWriter writer, GeneratedTypeCode typeCode)
        {
            writer.Append($"{Indent}{Indent}{WriteMetadataArray("PropertyMethodMetadata", SortProperties(typeCode.Properties).Select(GetPropertyMetadataEntry))}");
        }

        private static void WriteGroupedMetadata(CodeWriter writer, GeneratedTypeCode typeCode)
        {
            writer.Append($"{Indent}{Indent}{WriteMetadataArray("GroupedPropertyMethodMetadata", GetGroupedSurfaces(typeCode).Select(GetGroupedMetadataEntry))}");
        }

        private static void WriteAttachedMetadata(CodeWriter writer, GeneratedTypeCode typeCode)
        {
            writer.Append($"{Indent}{Indent}{WriteMetadataArray("AttachedPropertyMethodMetadata", SortAttachedTypes(typeCode.AttachedTypes).Select(GetAttachedMetadataEntry))}");
        }

        private static void WriteSignalMetadata(CodeWriter writer, GeneratedTypeCode typeCode)
        {
            writer.Append($"{Indent}{Indent}{WriteMetadataArray("SignalMethodMetadata", SortSignals(typeCode.Signals).Select(GetSignalMetadataEntry))}");
        }

        private static string WriteMetadataArray(string typeName, IEnumerable<string> entries)
        {
            string[] orderedEntries = entries.ToArray();
            if (orderedEntries.Length == 0)
            {
                return $"ImmutableArray<{typeName}>.Empty";
            }

            return $"ImmutableArray.Create<{typeName}>({string.Join(", ", orderedEntries)})";
        }

        private static string GetPropertyMetadataEntry(GeneratedProperty property)
        {
            string qmlPropertyName = GetQmlPropertyName(property);
            string supportsValue = property.IsReadOnly ? "false" : "true";
            string supportsBinding = string.IsNullOrWhiteSpace(property.BindSignature) ? "false" : "true";
            return $"new PropertyMethodMetadata(\"{EscapeStringLiteral(property.Name)}\", \"{EscapeStringLiteral(qmlPropertyName)}\", {supportsValue}, {supportsBinding})";
        }

        private static string GetGroupedMetadataEntry(GroupedSurface groupedSurface)
        {
            string collectorMetadata = GetCollectorMetadata(groupedSurface.Properties, ImmutableArray<GeneratedSignal>.Empty);
            return $"new GroupedPropertyMethodMetadata(\"{EscapeStringLiteral(groupedSurface.GroupName)}\", \"{EscapeStringLiteral(GetQmlGroupName(groupedSurface))}\", {collectorMetadata})";
        }

        private static string GetAttachedMetadataEntry(GeneratedAttachedType attachedType)
        {
            string collectorMetadata = GetCollectorMetadata(attachedType.Properties, attachedType.Signals);
            return $"new AttachedPropertyMethodMetadata(\"{EscapeStringLiteral(attachedType.MethodName)}\", \"{EscapeStringLiteral(attachedType.MethodName)}\", {collectorMetadata})";
        }

        private static string GetSignalMetadataEntry(GeneratedSignal signal)
        {
            return $"new SignalMethodMetadata(\"{EscapeStringLiteral(signal.HandlerName)}\", \"{EscapeStringLiteral(NameConventionsSignalName(signal.HandlerName))}\")";
        }

        private static string GetCollectorMetadata(
            ImmutableArray<GeneratedProperty> properties,
            ImmutableArray<GeneratedSignal> signals)
        {
            string propertyMetadata = WriteMetadataArray("PropertyMethodMetadata", SortProperties(properties).Select(property =>
            {
                string methodName = IsGroupedProperty(property) ? GetLocalGroupedMethodName(property) : property.Name;
                string supportsValue = property.IsReadOnly ? "false" : "true";
                string supportsBinding = string.IsNullOrWhiteSpace(property.BindSignature) ? "false" : "true";
                return $"new PropertyMethodMetadata(\"{EscapeStringLiteral(methodName)}\", \"{EscapeStringLiteral(GetLocalQmlPropertyName(property))}\", {supportsValue}, {supportsBinding})";
            }));
            string signalMetadata = WriteMetadataArray("SignalMethodMetadata", SortSignals(signals).Select(GetSignalMetadataEntry));
            return $"new PropertyCollectorMetadata({propertyMetadata}, {signalMetadata})";
        }

        private static string EnsureInterfaceSignature(string signature)
        {
            string trimmed = signature.Trim();
            return trimmed.EndsWith(";", StringComparison.Ordinal) ? trimmed[..^1] : trimmed;
        }

        private static ImmutableArray<string> GetTypeFileUsings()
        {
            ImmutableArray<string>.Builder usings = ImmutableArray.CreateBuilder<string>();
            usings.Add("System");
            usings.Add("System.Collections.Immutable");
            usings.Add("QmlSharp.Core");
            usings.Add("QmlSharp.Dsl");

            return usings
                .Distinct(StringComparer.Ordinal)
                .Order(StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static void WriteXmlDoc(CodeWriter writer, CodeEmitOptions options, string summary, string indent = "")
        {
            if (!options.GenerateXmlDoc)
            {
                return;
            }

            writer.AppendLine($"{indent}/// <summary>");
            writer.AppendLine($"{indent}/// {EscapeXml(summary)}");
            writer.AppendLine($"{indent}/// </summary>");
        }

        private static void WriteGeneratedXmlDoc(CodeWriter writer, CodeEmitOptions options, string xmlDoc, string indent = "")
        {
            if (!options.GenerateXmlDoc)
            {
                return;
            }

            string content = xmlDoc.Trim();
            if (content.StartsWith("<summary>", StringComparison.Ordinal)
                && content.EndsWith("</summary>", StringComparison.Ordinal))
            {
                content = content["<summary>".Length..^"</summary>".Length].Trim();
            }

            WriteXmlDoc(writer, options, content, indent);
        }

        private static ImmutableArray<GeneratedProperty> SortProperties(ImmutableArray<GeneratedProperty> properties)
        {
            return properties
                .OrderBy(static property => property.Name, StringComparer.Ordinal)
                .ThenBy(static property => property.CSharpType, StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static ImmutableArray<GeneratedSignal> SortSignals(ImmutableArray<GeneratedSignal> signals)
        {
            return signals
                .OrderBy(static signal => signal.HandlerName, StringComparer.Ordinal)
                .ThenBy(static signal => signal.SignalName, StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static ImmutableArray<GeneratedMethod> SortMethods(ImmutableArray<GeneratedMethod> methods)
        {
            return methods
                .OrderBy(static method => method.Name, StringComparer.Ordinal)
                .ThenBy(static method => method.Signature, StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static ImmutableArray<GeneratedEnum> SortEnums(ImmutableArray<GeneratedEnum> enums)
        {
            return enums
                .OrderBy(static generatedEnum => generatedEnum.Name, StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static ImmutableArray<GeneratedAttachedType> SortAttachedTypes(ImmutableArray<GeneratedAttachedType> attachedTypes)
        {
            return attachedTypes
                .OrderBy(static attachedType => attachedType.MethodName, StringComparer.Ordinal)
                .ThenBy(static attachedType => attachedType.TypeName, StringComparer.Ordinal)
                .ToImmutableArray();
        }

        private static ImmutableArray<GroupedSurface> GetGroupedSurfaces(GeneratedTypeCode typeCode)
        {
            return SortProperties(typeCode.Properties)
                .Where(static property => IsGroupedProperty(property))
                .GroupBy(static property => GetGroupName(property), StringComparer.Ordinal)
                .OrderBy(static group => group.Key, StringComparer.Ordinal)
                .Select(static group =>
                {
                    string groupName = group.Key;
                    return new GroupedSurface(
                        GroupName: groupName,
                        BuilderInterfaceName: $"I{groupName}Builder",
                        Properties: group.OrderBy(static property => GetLocalGroupedMethodName(property), StringComparer.Ordinal).ToImmutableArray());
                })
                .ToImmutableArray();
        }

        private static bool IsGroupedProperty(GeneratedProperty property)
        {
            return GetQmlPropertyName(property).Contains('.', StringComparison.Ordinal);
        }

        private static string GetGroupName(GeneratedProperty property)
        {
            string qmlPropertyName = GetQmlPropertyName(property);
            int separatorIndex = qmlPropertyName.IndexOf('.', StringComparison.Ordinal);
            return ToPascalCase(separatorIndex < 0 ? qmlPropertyName : qmlPropertyName[..separatorIndex]);
        }

        private static string GetQmlGroupName(GroupedSurface groupedSurface)
        {
            GeneratedProperty firstProperty = groupedSurface.Properties[0];
            string qmlPropertyName = GetQmlPropertyName(firstProperty);
            int separatorIndex = qmlPropertyName.IndexOf('.', StringComparison.Ordinal);
            return separatorIndex < 0 ? qmlPropertyName : qmlPropertyName[..separatorIndex];
        }

        private static string GetLocalGroupedMethodName(GeneratedProperty property)
        {
            string qmlPropertyName = GetQmlPropertyName(property);
            int separatorIndex = qmlPropertyName.IndexOf('.', StringComparison.Ordinal);
            return ToPascalCase(separatorIndex < 0 ? qmlPropertyName : qmlPropertyName[(separatorIndex + 1)..]);
        }

        private static string GetLocalQmlPropertyName(GeneratedProperty property)
        {
            string qmlPropertyName = GetQmlPropertyName(property);
            int separatorIndex = qmlPropertyName.IndexOf('.', StringComparison.Ordinal);
            return separatorIndex < 0 ? qmlPropertyName : qmlPropertyName[(separatorIndex + 1)..];
        }

        private static string GetQmlPropertyName(GeneratedProperty property)
        {
            string? matched = property.DeclaredBy.Properties
                .Where(qmlProperty => string.Equals(ToPascalCase(qmlProperty.Name), property.Name, StringComparison.Ordinal))
                .Select(static qmlProperty => qmlProperty.Name)
                .Order(StringComparer.Ordinal)
                .FirstOrDefault();

            return matched ?? ToCamelCase(property.Name);
        }

        private static string NameConventionsSignalName(string handlerName)
        {
            string localName = handlerName.StartsWith("On", StringComparison.Ordinal) ? handlerName[2..] : handlerName;
            return $"on{localName}";
        }

        private static string GetIndexModuleUri(ImmutableArray<GeneratedTypeCode> types, ImmutableArray<GeneratedEnum> enums)
        {
            string? moduleUri = types
                .Select(static type => type.ModuleUri)
                .Where(static moduleUri => !string.IsNullOrWhiteSpace(moduleUri))
                .Order(StringComparer.Ordinal)
                .FirstOrDefault();
            if (moduleUri is not null)
            {
                return moduleUri;
            }

            return enums
                .Select(static generatedEnum => generatedEnum.OwnerType.ModuleUri)
                .Where(static moduleUri => !string.IsNullOrWhiteSpace(moduleUri))
                .Order(StringComparer.Ordinal)
                .FirstOrDefault()
                ?? "QmlSharp.Generated";
        }

        private static string GetNamespace(string moduleUri)
        {
            if (string.IsNullOrWhiteSpace(moduleUri))
            {
                return "QmlSharp.Generated";
            }

            string suffix = string.Join(
                ".",
                moduleUri
                    .Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                    .Select(ToPascalCase));
            return suffix.StartsWith("QmlSharp.", StringComparison.Ordinal) || string.Equals(suffix, "QmlSharp", StringComparison.Ordinal)
                ? suffix
                : $"QmlSharp.{suffix}";
        }

        private static string GetModuleClassName(string moduleUri)
        {
            return string.Concat(moduleUri.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(ToPascalCase));
        }

        private static string ToPascalCase(string name)
        {
            string[] parts = name.Split(['.', '-', '_', ':', ' '], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (parts.Length == 0)
            {
                return "_";
            }

            return string.Concat(parts.Select(static part => string.Concat(char.ToUpperInvariant(part[0]).ToString(), part[1..])));
        }

        private static string ToCamelCase(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return name;
            }

            return string.Concat(char.ToLowerInvariant(name[0]).ToString(), name[1..]);
        }

        private static string EscapeStringLiteral(string value)
        {
            return value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
        }

        private static string EscapeXml(string value)
        {
            return value
                .Replace("&", "&amp;", StringComparison.Ordinal)
                .Replace("<", "&lt;", StringComparison.Ordinal)
                .Replace(">", "&gt;", StringComparison.Ordinal)
                .Replace("\"", "&quot;", StringComparison.Ordinal);
        }

        private static IEnumerable<string> NormalizeLines(string value)
        {
            return value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n').Split('\n');
        }

        private static void ThrowIfInvalidType(GeneratedTypeCode typeCode)
        {
            if (string.IsNullOrWhiteSpace(typeCode.QmlName))
            {
                throw new DslGenerationException(
                    "Cannot emit a type file without a QML type name.",
                    DslDiagnosticCodes.EmitFailure,
                    typeCode.QmlName,
                    typeCode.ModuleUri);
            }

            if (string.IsNullOrWhiteSpace(typeCode.ModuleUri))
            {
                throw new DslGenerationException(
                    $"Cannot emit type '{typeCode.QmlName}' without a module URI.",
                    DslDiagnosticCodes.EmitFailure,
                    typeCode.QmlName,
                    typeCode.ModuleUri);
            }

            if (string.IsNullOrWhiteSpace(typeCode.BuilderInterfaceName)
                || string.IsNullOrWhiteSpace(typeCode.PropsInterfaceName))
            {
                throw new DslGenerationException(
                    $"Cannot emit type '{typeCode.QmlName}' without generated interface names.",
                    DslDiagnosticCodes.EmitFailure,
                    typeCode.QmlName,
                    typeCode.ModuleUri);
            }
        }

        private sealed record GroupedSurface(
            string GroupName,
            string BuilderInterfaceName,
            ImmutableArray<GeneratedProperty> Properties);

        private sealed class CodeWriter
        {
            private readonly StringBuilder _builder = new();

            public void Append(string value)
            {
                _builder.Append(value);
            }

            public void AppendLine()
            {
                _builder.Append('\n');
            }

            public void AppendLine(string value)
            {
                _builder.Append(value);
                _builder.Append('\n');
            }

            public override string ToString()
            {
                return _builder.ToString();
            }
        }
    }
}
