using QmlSharp.Dsl.Generator.Tests.Fixtures;

namespace QmlSharp.Dsl.Generator.Tests.Emitter
{
    public sealed class FormattingAssumptionsTests
    {
        [Fact]
        public void EmitTypeFile_GeneratedCSharp_UsesAnalyzerFriendlyFormattingAssumptions()
        {
            CodeEmitter emitter = new();

            string source = emitter.EmitTypeFile(DslTestFixtures.CreateGeneratedRectangleMetadata(), DslTestFixtures.DefaultEmitOptions);

            Assert.StartsWith("// <auto-generated />\n\n#nullable enable\n", source, StringComparison.Ordinal);
            Assert.DoesNotContain("\r", source, StringComparison.Ordinal);
            Assert.DoesNotContain("\t", source, StringComparison.Ordinal);
            Assert.All(
                source.Split('\n'),
                line => Assert.Equal(line.TrimEnd(), line));
            Assert.Contains("using QmlSharp.Core;\nusing QmlSharp.Dsl;\nusing System;\nusing System.Collections.Immutable;\n", source, StringComparison.Ordinal);
        }

        [Fact]
        public void EmitProjectFile_PackageDependencies_AreOrdinalAndStable()
        {
            GeneratedPackage package = new(
                PackageName: "QmlSharp.QtQuick.Controls",
                ModuleUri: "QtQuick.Controls",
                PackageVersion: "0.1.0",
                Files: ImmutableArray<GeneratedFile>.Empty,
                Types: 0,
                Dependencies: ["QmlSharp.QtQuick", "QmlSharp.Core", "QmlSharp.Dsl"],
                Stats: new PackageStats(0, 0, 0, 0, 0, 0, 0));
            CodeEmitter emitter = new();

            string project = emitter.EmitProjectFile(package);

            Assert.True(
                project.IndexOf("Include=\"QmlSharp.Core\"", StringComparison.Ordinal)
                < project.IndexOf("Include=\"QmlSharp.Dsl\"", StringComparison.Ordinal));
            Assert.True(
                project.IndexOf("Include=\"QmlSharp.Dsl\"", StringComparison.Ordinal)
                < project.IndexOf("Include=\"QmlSharp.QtQuick\"", StringComparison.Ordinal));
            Assert.DoesNotContain("\r", project, StringComparison.Ordinal);
            Assert.All(
                project.Split('\n'),
                line => Assert.Equal(line.TrimEnd(), line));
        }
    }
}
