using System.Collections.Immutable;
using QmlSharp.Qml.Ast;

#pragma warning disable MA0048

namespace QmlSharp.Dsl
{
    /// <summary>
    /// Base interface for all QML object builders generated by QmlSharp.
    /// </summary>
    public interface IObjectBuilder
    {
        /// <summary>Gets the QML type name represented by this builder.</summary>
        string QmlTypeName { get; }

        /// <summary>Assigns the QML id for this object.</summary>
        IObjectBuilder Id(string id);

        /// <summary>Adds a child object to this object.</summary>
        IObjectBuilder Child(IObjectBuilder child);

        /// <summary>Adds child objects to this object in the given order.</summary>
        IObjectBuilder Children(params IObjectBuilder[] children);

        /// <summary>Adds a literal property binding.</summary>
        IObjectBuilder SetProperty(string propertyName, object? value);

        /// <summary>Adds a QML expression binding.</summary>
        IObjectBuilder SetBinding(string propertyName, string expression);

        /// <summary>Adds grouped property bindings.</summary>
        IObjectBuilder AddGrouped(string groupName, Action<IPropertyCollector> configure);

        /// <summary>Adds attached property bindings.</summary>
        IObjectBuilder AddAttached(string attachedTypeName, Action<IPropertyCollector> configure);

        /// <summary>Adds a signal handler body.</summary>
        IObjectBuilder HandleSignal(string handlerName, string body);

        /// <summary>Builds the immutable QML AST object node.</summary>
        ObjectDefinitionNode Build();
    }

    /// <summary>
    /// Collects property, binding, and signal entries for grouped or attached builder callbacks.
    /// </summary>
    public interface IPropertyCollector
    {
        /// <summary>Gets entries collected so far in insertion order.</summary>
        ImmutableArray<PropertyCollectionEntry> Entries { get; }

        /// <summary>Adds a literal property binding.</summary>
        IPropertyCollector SetProperty(string propertyName, object? value);

        /// <summary>Adds a QML expression binding.</summary>
        IPropertyCollector SetBinding(string propertyName, string expression);

        /// <summary>Adds a signal handler entry.</summary>
        IPropertyCollector HandleSignal(string handlerName, string body);
    }

    /// <summary>
    /// Factory entry point used by generated DSL package factory methods.
    /// </summary>
    public static class ObjectFactory
    {
        /// <summary>Creates a generated builder instance for the specified QML type.</summary>
        /// <typeparam name="TBuilder">The generated builder interface type.</typeparam>
        /// <param name="qmlTypeName">The QML type name to construct.</param>
        /// <returns>A builder implementing <typeparamref name="TBuilder"/>.</returns>
        public static TBuilder Create<TBuilder>(string qmlTypeName)
            where TBuilder : class, IObjectBuilder
        {
            return Create<TBuilder>(qmlTypeName, ObjectBuilderMetadata.Empty);
        }

        /// <summary>Creates a generated builder instance with method metadata.</summary>
        /// <typeparam name="TBuilder">The generated builder interface type.</typeparam>
        /// <param name="qmlTypeName">The QML type name to construct.</param>
        /// <param name="metadata">Metadata used to map generated method names to QML names.</param>
        /// <returns>A builder implementing <typeparamref name="TBuilder"/>.</returns>
        public static TBuilder Create<TBuilder>(string qmlTypeName, ObjectBuilderMetadata metadata)
            where TBuilder : class, IObjectBuilder
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(qmlTypeName);
            ArgumentNullException.ThrowIfNull(metadata);

            TBuilder proxy = DispatchProxyFactory.CreateObjectProxy<TBuilder>(qmlTypeName, metadata);
            return proxy;
        }

        /// <summary>Creates the concrete runtime builder for tests and low-level generated code.</summary>
        /// <param name="qmlTypeName">The QML type name to construct.</param>
        /// <returns>A concrete object builder.</returns>
        public static ObjectBuilder Create(string qmlTypeName)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(qmlTypeName);
            return new ObjectBuilder(qmlTypeName);
        }
    }
}

#pragma warning restore MA0048
