#pragma warning disable MA0048

namespace QmlSharp.Dsl
{
    /// <summary>
    /// Base interface for all QML object builders generated by QmlSharp.
    /// </summary>
    public interface IObjectBuilder
    {
        /// <summary>Gets the QML type name represented by this builder.</summary>
        string QmlTypeName { get; }
    }

    /// <summary>
    /// Factory entry point used by generated DSL package factory methods.
    /// </summary>
    public static class ObjectFactory
    {
        /// <summary>Creates a generated builder instance for the specified QML type.</summary>
        /// <typeparam name="TBuilder">The generated builder interface type.</typeparam>
        /// <param name="qmlTypeName">The QML type name to construct.</param>
        /// <returns>A builder implementing <typeparamref name="TBuilder"/>.</returns>
        public static TBuilder Create<TBuilder>(string qmlTypeName)
            where TBuilder : IObjectBuilder
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(qmlTypeName);

            throw new NotSupportedException("Builder creation is not available until the DSL runtime implementation is added.");
        }
    }
}

#pragma warning restore MA0048
