using QmlSharp.Dsl.Generator.Tests.Fixtures;

namespace QmlSharp.Dsl.Generator.Tests.Pipeline
{
    public sealed class DefaultOptionsSmokeTests
    {
        [Fact]
        [Trait("Category", TestCategories.Smoke)]
        public void DefaultOptions_ExposeExpectedContractDefaults()
        {
            GenerationOptions options = DslTestFixtures.DefaultOptions;

            Assert.Null(options.TypeMapper);
            Assert.Equal(32, options.Inheritance.MaxDepth);
            Assert.True(options.Properties.GenerateBindMethods);
            Assert.Equal("On", options.Signals.HandlerPrefix);
            Assert.True(options.ViewModel.Enabled);
            Assert.Equal("Qml", options.ViewModel.ProxyPrefix);
            Assert.Equal("generated", options.Packager.OutputDir);
        }

        [Fact]
        [Trait("Category", TestCategories.Smoke)]
        public void DefaultEmitOptions_ExposeExpectedContractDefaults()
        {
            CodeEmitOptions options = DslTestFixtures.DefaultEmitOptions;

            Assert.True(options.GenerateXmlDoc);
            Assert.True(options.MarkDeprecated);
            Assert.Equal("// <auto-generated />", options.HeaderComment);
        }
    }
}
