function(qmlsharp_enable_sanitizers target_name)
  if(NOT ENABLE_ASAN)
    return()
  endif()

  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
    target_link_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
  else()
    message(WARNING "ENABLE_ASAN is currently supported only for Clang/GCC toolchains.")
  endif()
endfunction()
